### ISSUE TITLE
List tournaments

### ISSUE THREAD

**Issue by julioolvr** [julioolvr/challonge-dashboard#1]
Being able to list tournaments instead of having to paste the URL.

It seems Challonge's API can only list tournaments created by a given user: https://api.challonge.com/v1/documents/tournaments/index

Also, to list tournaments in an organization then the `subdomain` parameter is required. And it doesn't seem there's a way to list the organizations a user has.

Maybe an easy and useful idea would be to store in `localStorage` a history of looked up tournaments and allow to go back and forth between those.

**Comment by pechitook** [comment]
Esto ya fue, no?

**Comment by julioolvr** [comment]
Sep, totalmente
